# Generated by Django 5.1.2 on 2025-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_reset_code_user_reset_code_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinproblem',
            name='skin_problem_name',
            field=models.CharField(blank=True, choices=[('acne_prone', 'Acne Prone'), ('sensitive', 'Sensitive'), ('aging', 'Aging'), ('dry', 'Dry'), ('oily', 'Oily'), ('normal', 'Normal'), ('combination', 'Combination'), ('rosacea', 'Rosacea'), ('eczema', 'Eczema'), ('hyperpigmentation', 'Hyperpigmentation')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skintype',
            name='skin_type_name',
            field=models.CharField(blank=True, choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], max_length=50, null=True),
        ),
    ]
