# Generated by Django 5.1.2 on 2025-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_skinproblem_skin_problem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skin_problem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skin_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SkinProblem',
        ),
        migrations.DeleteModel(
            name='SkinType',
        ),
    ]
