# Generated by Django 5.1.2 on 2025-03-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skin_problem',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skin_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
