# Generated by Django 5.1.2 on 2025-04-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_skin_problem_alter_user_skin_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='birth_year',
        ),
    ]
